#############
### RULES ###
#############

# "Smart gaps" / "No gaps when only"
workspace = r[$ws7-$ws10] w[tv1], gapsout:0, gapsin:0
windowrule = match:workspace r[$ws7-$ws10] w[tv1], match:float 0, border_size 0
windowrule = match:workspace r[$ws7-$ws10] w[tv1], match:float 0, rounding 0

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class *, suppress_event maximize

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_initial_focus on

# Assign workspaces
# Discord
windowrule = match:class ^(discord)$, workspace $ws7 silent
# Deezer
windowrule = match:class ^(deezer-discord-rpc)$, workspace $ws9 silent

# Floating rules
windowrule = match:title (?:Open|Save) (?:File|Folder|As), float on
windowrule = match:title (?:Open|Save) (?:File|Folder|As), size 1030 710
# MPV
windowrule = match:class ^(mpv)$, float on
windowrule = match:class ^(mpv)$, size 960 540
windowrule = match:class ^(mpv)$, border_size 0
# Firefox
windowrule = match:class ^(firefox)$, match:title ^(Firefox – Sharing Indicator)$, float on
windowrule = match:class ^(firefox)$, match:title ^(Picture-in-Picture)$, float on
windowrule = match:class ^(firefox)$, match:title ^(Pushbullet – Mozilla Firefox)$, float on
windowrule = match:class ^(firefox)$, match:title ^(About Mozilla Firefox)$, float on
windowrule = match:class ^(firefox)$, match:title (— Firefox)$, float on
windowrule = match:class ^(firefox)$, match:title ^(Firefox)$, float on
# Thunar
windowrule = match:class ^(thunar)$, match:title ^(Copying).*, float on
windowrule = match:class ^(thunar)$, match:title ^(File).*, float on
# Steam
windowrule = match:class ^(steam)$, float on
windowrule = match:class ^(steam)$, match:title ^(Steam)$, tile on
# kDrive
windowrule = match:class ^(kDrive)$, fullscreen on

# Inhibit idle
# All fullscreen apps
windowrule = match:class .*, idle_inhibit fullscreen

# MPV
windowrule = match:class ^(mpv)$, idle_inhibit focus

# Games
# Counter Strike 2
windowrule = match:class ^(cs2)$, match:title ^(Counter-Strike 2)$, fullscreen on

# Guild Wars 2
windowrule = match:class ^(steam_app_1284210|gw2-64.exe)$, match:title ^(Guild Wars 2)$, border_size 0
windowrule = match:class ^(steam_app_1284210|gw2-64.exe)$, match:title ^(Guild Wars 2)$, no_blur on
windowrule = match:class ^(steam_app_1284210|gw2-64.exe)$, match:title ^(Guild Wars 2)$, decorate off

# Rise of the Tomb Raider
windowrule = match:class ^(steam_app_391220)$, match:title ^(Rise of the Tomb Raider v).*, fullscreen on
